apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alqemam-pvc
  namespace: production
  labels:
    app: api-alqemam
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
